#general.import = ["/home/sangharsha/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"]
general.import = ["/home/sangharsha/.config/alacritty/themes/gruvbox_material_medium_dark.toml"]
general.live_config_reload = true

[window]
decorations = "None"
dimensions = {columns = 100, lines = 27}
dynamic_padding = true
opacity = 1.0
padding = {x=20, y=20}
blur = true

[font]
size = 13

[font.normal]
family = "CaskaydiaMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[terminal.shell]
program = "/usr/bin/zsh"
